artifacts_root: artifacts


data_ingestion:
 root_dir: artifacts/data_ingestion
 source_URL: https://drive.google.com/file/d/1vSKBeu6iWGDHbUj39pfgpmbRj74TQp5D/view?usp=sharing
 local_data_file: artifacts/data_ingestion/data.zip
 unzip_data: artifacts/data_ingestion


data_validation:
 root_dir: artifacts/data_validation
 data_path: artifacts/data_ingestion/hour.csv
 STATUS_INFO: artifacts/data_validation/status.txt


data_transformation:
 root_dir: artifacts/data_transformation
 data_path: artifacts/data_ingestion/hour.csv


model_trainer:
 root_dir: artifacts/model_trainer
 train_data_path: artifacts/data_transformation/train.csv
 test_data_path: artifacts/data_transformation/test.csv
 model_name: model.joblib

model_evalution:
 root_dir: artifacts/model_evalution
 test_data_path: artifacts/data_transformation/test.csv
 model_path: artifacts/model_trainer/model.joblib
 metric_file_name: artifacts/model_evalution/metrics.json